### ISSUE TITLE
Something's wrong with Dockerfile 😕

### ISSUE THREAD

**Issue by zeljkofilipin** [zeljkofilipin/filipin.eu#2]
[Dockerfile](https://github.com/zeljkofilipin/filipin.eu/blob/master/Dockerfile) is pretty simple:

```dockerfile
# This file was created by referencing:
# https://docs.docker.com/geot-started/part2/#sample-dockerfile
# https://hub.docker.com/_/Ruby

# Use the official image as a parent image.
FROM ruby:2.7

# Throw errors if Gemfile has been modified since Gemfile.lock.
RUN bundle config --global frozen 1

# Set the working directory.
WORKDIR /usr/src/app

# Copy the file from your host to your current location.
COPY Gemfile Gemfile.lock ./

# Run the command inside your image filesystem.
RUN bundle install

# Add metadata to the image to describe which port the container is listening on at runtime.
EXPOSE 4000

# Copy the rest of your app's source code from your host to your image filesystem.
COPY . .

# Run the specified command within the container.
CMD ["bundle", "exec", "jekyll", "serve"]
```

I can build the image.

```
~/Documents/github/zeljkofilipin/filipin.eu$ docker build --tag blog:0.7 .                                     
Sending build context to Docker daemon  42.64MB
Step 1/8 : FROM ruby:2.7
 ---> cd155aa807df
Step 2/8 : RUN bundle config --global frozen 1
 ---> Using cache
 ---> 6529d7c843d9
Step 3/8 : WORKDIR /usr/src/app
 ---> Using cache
 ---> 2f3cd053235f
Step 4/8 : COPY Gemfile Gemfile.lock ./
 ---> Using cache
 ---> 00a415f7bcd9
Step 5/8 : RUN bundle install
 ---> Using cache
 ---> 031557305dc5
Step 6/8 : EXPOSE 4000
 ---> Using cache
 ---> 3b9a65d7033b
Step 7/8 : COPY . .
 ---> 89b29ee0de8f
Step 8/8 : CMD ["bundle", "exec", "jekyll", "serve"]
 ---> Running in 0729bce3dcdb
Removing intermediate container 0729bce3dcdb
 ---> 54899b4eb124
Successfully built 54899b4eb124
Successfully tagged blog:0.7
```

I can run the container.

```
~/Documents/github/zeljkofilipin/filipin.eu$ docker run --publish 4000:4000 --name blog-0.7.1 blog:0.7
Configuration file: /usr/src/app/_config.yml
            Source: /usr/src/app
       Destination: /usr/src/app/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
       Jekyll Feed: Generating feed for posts
                    done in 4.229 seconds.
 Auto-regeneration: enabled for '/usr/src/app'
    Server address: http://127.0.0.1:4000/
  Server running... press ctrl-c to stop.
```

As far as I can see, port 4000 from the container is forwarded to port 4000 on the host.

```
~/Documents/github/zeljkofilipin/filipin.eu$ docker ps   
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                    NAMES
1957e4ed4328        blog:0.7            "bundle exec jekyll …"   27 seconds ago      Up 26 seconds       0.0.0.0:4000->4000/tcp   blog-0.7.1
```

But, when I visit http://localhost:4000/ I get `The connection was reset` error page.

![the-connection-was-reset](https://user-images.githubusercontent.com/23927/100377357-66ab1f00-3011-11eb-93f6-84a83fc03e1d.png)

Please notice it is not the usual `Unable to connect` error page when the server is not running.

![unable-to-connect](https://user-images.githubusercontent.com/23927/100377367-6dd22d00-3011-11eb-8233-fc0110103135.png)

**Comment by und3fined-v01d** [comment]
@zeljkofilipin while running you need to expose your local machines port to Dockers port. Try running the container with a -p 8080:8080 flag

**Comment by dancysoft** [comment]
This is happening because the jekyll process inside the container is listening on localhost:4000 instead of 0.0.0.0:4000.  This means that it will only accept connections made from 127.0.0.1.  When you do `docker run --publish 4000:4000 --name blog-0.7.1 blog:0.7` docker starts a `docker-proxy` process.  Here's what it looks like on my system:
`/usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 4000 -container-ip 172.17.0.2 -container-port 4000`
So, if you attempt to connect to localhost:4000 on the host, docker-proxy answers and it makes a connection to 172.17.0.2:4000. 172.17.0.2 if the container's IP address.  Since this is not 127.0.0.1, the kernel will reject the connection.

I was able to deal with this by modifying the last line of the Dockerfile:
`CMD ["bundle", "exec", "jekyll", "serve","-H","0.0.0.0"]`
xref: https://jekyllrb.com/docs/configuration/options/#serve-command-options

**Comment by zeljkofilipin** [comment]
@dancysoft Thanks! It works! 🥳
